version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - bundle install --path vendor/bundle
  pre_build:
    commands:
      - export LC_ALL="C.UTF-8"
      - export LANG="en_US.UTF-8"
      - export LANGUAGE="en_US.UTF-8"
  build:
    commands:
      - bundler exec jekyll build
  post_build:
    commands:
      - aws s3 sync --delete --size-only --cache-control max-age=7201 _site/ "s3://${BUCKET_NAME}"
      - aws s3api put-bucket-website --bucket "${BUCKET_NAME}" --website-configuration file://s3-website-config.json
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
cache:
  paths:
    - 'vendor/**/*'
