---
layout: wordpress-import
status: publish
published: true
title: 'Thursday Threads: Twitter Timeline Changes, Report on Future Library Technology, USB Security'
modified: 2014-08-21T10:48:38+00:00
author: Peter Murray
author_login: lyrdor
author_email: jester@dltj.org
author_url: http://dltj.org/about
wordpress_id: 19443
wordpress_url: http://dltj.org/?p=19443
date: '2014-08-21 06:48:38 -0400'
date_gmt: '2014-08-21 10:48:38 -0400'
categories:
- Thursday Threads
tags:
- higher education
- academic libraries
- Twitter
- security
- trends
- Facebook
- usb
comments:
- id: 669480
  author: Stephen Michael Kellat
  author_email: smkellat@yahoo.com
  author_url: ''
  date: '2014-11-21 17:09:07 -0500'
  date_gmt: '2014-11-21 22:09:07 -0500'
  content: After the number of times Twitter pushed very hard the notion of buying
    ads, I gave up on it.  With these timeline changes...I think I can live without
    it.
---
<div id="feedburner-thursday-threads-email-2014w33" class="wp-caption alignright noprint noFrontPage" style="width: 230px;">
<form style="border: 1px solid rgb(204, 204, 204); padding: 3px; margin: 0pt; text-align: center;" action="http://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=thursday-threads', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">Receive <i><acronym title="Disruptive Library Technology Jester">DLTJ</acronym></i> Thursday Threads:</p>
<p>by&nbsp;<a href="http://feedburner.google.com/fb/a/mailverify?uri=thursday-threads&amp;loc=en_US" title="D.L.T.J. Thursday Threads Email Subscription">E-mail</a><br /><input style="width: 140px;" name="email" value="Your e-mail address" onfocus="if (this.defaultValue==this.value) this.value = ''" type="text"/><input value="thursday-threads" name="uri" type="hidden"/><input name="loc" value="en_US" type="hidden"/><input value="Subscribe" type="submit"/></p>
<p>by&nbsp;<a href="http://feeds.dltj.org/thursday-threads/" title="D.L.T.J. Thursday Threads RSS Feed">RSS</a>
<p style="font-size: 80%;">Delivered by <a href="http://feedburner.google.com" target="_blank" title="Google Feedburner Service">FeedBurner</a></p>
</form>
</div>
<p>Two weeks in a row!  This week's <i><acronym title="Disruptive Library Technology Jester">DLTJ</acronym> Thursday Threads</i> looks at how <a href="/article/thursday-threads-2014w33/#p19443-twitter">Twitter changed its timeline functionality</a> to include things that it thinks you'll find interesting.  Next, for the academic libraries in the audience, is a report from the New Media Consortium on <a href="/article/thursday-threads-2014w33/#p19443-library-horizon-report">trends and technologies that will libraries will likely encounter</a> in the next five years.  Lastly, news about research into how <a href="/article/thursday-threads-2014w33/#p19443-usb-malware">USB devices can spread malware in ways we can't detect</a>.</p>
<p>Feel free to send this to others you think might be interested in the topics.  If you find these threads interesting and useful, you might want to add the <a title="RSS Feed for DLTJ Thursday Threads" href="http://feeds.dltj.org/thursday-threads/">Thursday Threads RSS Feed</a> to your feed reader or subscribe to e-mail delivery using the form to the right.  If you would like a more raw and immediate version of these types of stories, watch <a title="Peter Murray | Pinboard" href="http://pinboard.in/u:dltj">my Pinboard bookmarks</a> (or subscribe to <a title="RSS feed for Peter Murray's Pinboard account" href="http://feeds.pinboard.in/rss/u:dltj/">its feed</a> in your feed reader).  Items posted to are also sent out as <a title="Peter Murray's Twitter page" href="https://twitter.com/DataG">tweets</a>; you can <a target="_blank" href="https://twitter.com/intent/user?screen_name=DataG">follow me on <span style="background-image: url('//si0.twimg.com/images/dev/cms/intents/bird/bird_blue/bird_16_blue.png'); background-repeat: no-repeat; padding-left: 18px;">Twitter</span></a>.  Comments and tips, as always, are <a href="/contact">welcome</a>.</p>
<h2 id="p19443-twitter">Your Twitter Timeline is No Longer Your Own</h2>
<blockquote><p>Twitter recently began adding tweets to your timeline that have been favorited by people you follow. The decision has been a controversial one, but it looks like it&rsquo;s here to stay. Twitter has now formally changed its definition of your home timeline to note that it will add in content that it thinks you&rsquo;ll want to see.
<div style="text-align: right; width: 100%;"><cite>- <a href="http://thenextweb.com/twitter/2014/08/20/get-used-tweets-people-dont-follow-twitter-timeline-now-official-feature/" title="Tweets from People You Don&rsquo;t Follow in Your Twitter Timeline Are Here to Stay | The Next Web">Tweets from People You Don&rsquo;t Follow in Your Twitter Timeline Are Here to Stay</a>, by <a href="http://thenextweb.com/author/joshong/" title="Josh Ong, Author at The Next Web">Josh Ong</a>, The Next Web, 19-Aug-2014</cite></div>
</blockquote>
<blockquote><p>Additionally, when we identify a Tweet, an account to follow, or other content that's popular or relevant, we may add it to your timeline. This means you will sometimes see Tweets from accounts you don't follow. We select each Tweet using a variety of signals, including how popular it is and how people in your network are interacting with it. Our goal is to make your home timeline even more relevant and interesting.
<div style="text-align: right; width: 100%;"><cite>- <a href="https://support.twitter.com/articles/164083-what-s-a-twitter-timeline" title="What's a Twitter timeline? | Twitter Help Center"> What's a Twitter timeline?</a>, Twitter Help Center</cite></div>
</blockquote>
<p>Twitter was one of the last social network holdouts to not mess with its basic formula of what it showed you: what you saw in your timeline was based directly on who you subscribed to.  (Well, we'll ignore the sponsored tweet program for the moment.)  As The Next Web points out, Twitter has changed the definition of  &ldquo;<a href="https://support.twitter.com/articles/164083-what-s-a-twitter-timeline">What&rsquo;s a Twitter timeline?</a>&rdquo; page to include the second quote above.  This isn't full-blown filtering -- Twitter is not (yet?) deciding to remove uninteresting tweets from your timeline.  It is trying to show you other things that you may be interested in, though.</p>
<p>When I posted an <a href="http://thenextweb.com/twitter/2014/08/17/twitters-latest-experiment-turns-favorites-into-retweets-and-its-annoying-lots-of-people/" title="Twitter Tests Notifications for Favorites">earlier article from The Next Web</a> on LinkedIn about this change, <a href="https://www.linkedin.com/profile/view?id=10843982">Steve Casburn</a> noted the Medium article <a href="https://medium.com/message/ferguson-is-also-a-net-neutrality-issue-6d2f3db51eb0" title="The downside of algorithmic filtering | The Medium">The downside of algorithmic filtering</a>.  That article pointed out that while the author's Twitter timeline was full of tweets about the <a href="https://en.wikipedia.org/wiki/2014_Ferguson_unrest" title="2014 Ferguson unrest">police shooting and later civil unrest in Ferguson</a>, her Facebook wall was not -- it had not made it through the algorithmic exclusion filter that Facebook put in place.  The author goes on to ask, "what if Ferguson had started to bubble, but there was no Twitter to catch on nationally? Would it ever make it through the algorithmic filtering on Facebook? Maybe, but with no transparency to the decisions, I cannot be sure."</p>
<p>I get that Twitter is trying to increase its "<a href="https://en.wikipedia.org/wiki/Sticky_content" title="Sticky content | Wikipedia">stickiness</a>" by showing us things that it things will hold our interest right in line with things that we ask for.  I hope that Twitter doesn't decide to remove things that it things won't be interesting to us.  That would change the nature of Twitter dramatically and reduce its usefulness of getting outside of the "filter bubble."  (Interestingly, I've yet to see this new behavior myself in either Tweetdeck or the Twitter website.)</p>
<h2 id="p19443-library-horizon-report">A Glimpse at the Future: The Library Edition of the Horizon Report</h2>
<blockquote><p>The <em>NMC Horizon Report: 2014 Library Edition</em>, examines key trends, significant challenges, and emerging technologies for their potential impact on academic and research libraries worldwide. While there are many local factors affecting libraries, there are also issues that transcend regional boundaries and common questions; it was with these questions in mind that this report was created. The <em>NMC Horizon Report: 2014 Library Edition </em>was produced by the NMC in collaboration with University of Applied Sciences (HTW) Chur, Technische Informationsbibliothek (TIB) Hannover, and ETH-Bibliothek Zurich.&nbsp;To create the report, an international body of experts from library management, education, technology, and other fields was convened as a panel. Over the course of three months in the spring of 2014, the 2014 Horizon Project Library Expert Panel came to a consensus about the topics that would appear here in the <em>NMC Horizon Report: 2014 Library Edition</em>.
<div style="text-align: right; width: 100%;"><cite>- <a href="http://www.nmc.org/publications/2014-horizon-report-library" title="NMC Horizon Report for Academic Libraries 2014">NMC Horizon Report > 2014 Library Edition</a>, New Medium Consortium</cite></div>
</blockquote>
<p>For 12 years, the <a href="http://www.nmc.org/" title="The New Media Consortium | Sparking innovation, learning and creativity.">New Medium Consortium</a> (NMC) and the <a href="http://www.educause.edu/eli" title="EDUCAUSE Learning Initiative (ELI) homepage">EDUCAUSE Learning Initiative (ELI)</a> partnered to create the <a href="http://web.archive.org/web/20140218073621/http://www.nmc.org:80/horizon-project/horizon-reports/horizon-report-higher-ed-edition" title="The NMC Horizon Report: Higher Ed Edition | The New Media Consortium">Horizon Report on higher education</a>, a document that brings together practitioners to reach a consensus on emerging technologies in one-, three- and five-year time horizons.  This year, NMC and others partnered to create the first report geared towards academic and research libraries.  It covers topics like the evolving nature of the scholarly record and the rise of new forms of multidisciplinary research along with the adoption of technologies such as electronic publishing and bibliometrics.  This document is well researched and footnoted.  And if you want more depth, the <a href="http://library.wiki.nmc.org/" title="Horizon Report 2014 Library Edition Wiki">project wiki</a> is online with more details about the selected topics and <a href="http://library.wiki.nmc.org/Horizon+Topics" title="http://library.wiki.nmc.org/Horizon+Topics">other topics</a> that didn't filter to the top of the discussion.</p>
<h2 id="p19443-usb-malware">USB Flash Drives as Vectors for Malware</h2>
<blockquote><p>Most USB devices have a fundamental security weakness that can be exploited to infect computers with malware in a way that cannot easily be prevented or detected, security researchers found. The problem is that the majority of USB thumb drives, and likely other USB peripherals available on the market, do not protect their firmware -- the software that runs on the microcontroller inside them, said Karsten Nohl, the founder and chief scientist of Berlin-based Security Research Labs.
<div style="text-align: right; width: 100%;"><cite>- <a href="http://www.infoworld.com/d/security/most-usb-thumb-drives-can-be-reprogrammed-infect-computers-247489" title="Most USB thumb drives can be reprogrammed to infect computers | InfoWorld">Most USB thumb drives can be reprogrammed to infect computers</a>, by Lucian Constantin, InfoWorld, 1-Aug-2014</cite></div>
</blockquote>
<blockquote><p>Computer users pass around USB sticks like silicon business cards. Although we know they often carry malware infections, we depend on antivirus scans and the occasional reformatting to keep our thumbdrives from becoming the carrier for the next digital epidemic. But the security problems with USB devices run deeper than you think: Their risk isn&rsquo;t just in what they carry, it&rsquo;s built into the core of how they work.
<div style="text-align: right; width: 100%;"><cite>- <a href="http://www.wired.com/2014/07/usb-security/" title="Why the Security of USB Is Fundamentally Broken | Wired Threat Level blog">Why the Security of USB Is Fundamentally Broken</a>, by <a href="http://www.wired.com/author/andygreenberg/" title="Andy Greenberg | WIRED">Andy Greenberg</a>, Wired Threat Level blog, 31-Jul-2014</cite></div>
</blockquote>
<p>Can you trust that USB flash drive?  Arguably, no.  The problem lies in the software that runs on the flash drive itself.  Called the "firmware" it is that software that can be changed to, say, implant malware into files that are copied to and from the flash drive.  Or the flash drive could be programmed to emulate a keyboard and "type" nefarious commands to the operating system.  Or, most ingeniously in my mind, emulate a network adapter in such a way as to silently redirect all of you internet requests through a bad guy's server.</p>
<p>Why has USB become the main way to connect peripherals to computers?  Why hasn't anything replaced it?  Ars Technica has an in-depth article on the <a href="http://arstechnica.com/gadgets/2014/08/a-brief-history-of-usb-what-it-replaced-and-what-has-failed-to-replace-it/" title="A brief history of USB, what it replaced, and what has failed to replace it | Ars Technica">history of USB and other connectors that have tried to displace it</a>.</p>
